---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - threshold.shamir.io
  resources:
  - thresholdsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - threshold.shamir.io
  resources:
  - thresholdsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - threshold.shamir.io
  resources:
  - thresholdsecrets/status
  verbs:
  - get
  - patch
  - update
